on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  translate:
    runs-on: macos-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install plamo-translate
        run: uv tool install -p 3.12 plamo-translate
        shell: bash

      - name: Get Hugging Face Models cache info
        id: hf-cache
        run: |
          plamo_translate_model_dir_name="models--mlx-community--plamo-2-translate"
          echo "model-dir=${HOME}/.cache/huggingface/hub/${plamo_translate_model_dir_name}" >> $GITHUB_OUTPUT
          echo "plamo-translate-model=${plamo_translate_model_dir_name}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Download Hugging Face Models cache
        id: hf-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.hf-cache.outputs.model-dir }}
          key: ${{ runner.os }}-plamo-translate-model-${{ steps.hf-cache.outputs.plamo-translate-model }}
          restore-keys: |
            ${{ runner.os }}-plamo-translate-model-

      - name: Increase wired GPU memory limit if needed
        run: |
          current_limit_in_mib=$(uv run ./WiredGPUMemoryLimitInMiB.py)
          if (( current_limit_in_mib > MEMORY_FOR_MODEL_IN_MIB )); then
              echo "Current ${current_limit_in_mib} MiB limit is sufficient."
              exit 0
          fi

          physical_memory_in_mib=$(( $(sysctl -n hw.memsize) / 1024 / 1024))
          if (( MEMORY_FOR_MODEL_IN_MIB + MEMORY_FOR_SYSTEM_IN_MIB > physical_memory_in_mib )); then
              echo "Not enough physical memory available for allocating ${MEMORY_FOR_MODEL_IN_MIB} MiB."
              MEMORY_FOR_MODEL_IN_MIB=$(( physical_memory_in_mib - MEMORY_FOR_SYSTEM_IN_MIB ))
          fi

          sudo sysctl iogpu.wired_limit_mb="${MEMORY_FOR_MODEL_IN_MIB}"
          echo "Wired GPU memory limit set from ${current_limit_in_mib} to ${MEMORY_FOR_MODEL_IN_MIB} MiB."
        env:
          MEMORY_FOR_MODEL_IN_MIB: 5700
          MEMORY_FOR_SYSTEM_IN_MIB: 1024
        shell: bash

      - name: Run plamo-translate
        run: |
          SECONDS=0
          plamo-translate --from English --to Japanese < "LICENSE" > "LICENSE_ja"
          echo "Translation took $SECONDS seconds"
          cat "LICENSE_ja"
        shell: bash

      - name: Run plamo-translate server-style
        run: |
          SECONDS=0
          temp_dir="${RUNNER_TEMP}/plamo-translate-action"
          mkdir -p "${temp_dir}"

          FIFO_PIPE="${temp_dir}/server-output"
          mkfifo "${FIFO_PIPE}"
          (plamo-translate server > "${FIFO_PIPE}" 2>&1 ) &
          server_pid=$!
          grep -m 1 "running" "${FIFO_PIPE}" > /dev/null # Wait for the server to start

          plamo-translate --from English --to Japanese < "LICENSE" > "LICENSE_ja"
          echo "Translation took $SECONDS seconds"
          kill ${server_pid}
          rm -f "${FIFO_PIPE}"
          cat "LICENSE_ja"
        shell: bash

      - name: Run plamo-translate server-style-2
        run: |
          SECONDS=0
          temp_dir="${RUNNER_TEMP}/plamo-translate-action"
          mkdir -p "${temp_dir}"

          FIFO_PIPE="${temp_dir}/server-output"
          mkfifo "${FIFO_PIPE}"
          (plamo-translate server > "${FIFO_PIPE}" 2>&1 ) &
          server_pid=$!
          grep -m 1 "running" "${FIFO_PIPE}" > /dev/null # Wait for the server to start

          plamo-translate --from English --to Japanese < ".github/workflows/translate.yml" > "translate_ja.yml"
          echo "Translation took $SECONDS seconds"
          kill ${server_pid}
          rm -f "${FIFO_PIPE}"
          cat "translate_ja.yml"
        shell: bash


      - name: Cache Hugging Face Models
        if: ${{ steps.hf-cache-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.hf-cache.outputs.model-dir }}
          key: ${{ steps.hf-cache-restore.outputs.cache-primary-key }}